export enum StatusCodePhrases {
  ApiOnline = 'API_ONLINE',
  GuildAsserted = 'GUILD_ASSERTED',
  UserAsserted = 'USER_ASSERTED',
  UserNotFound = 'USER_NOT_FOUND',
  RouteNotFound = 'ROUTE_NOT_FOUND',
  MethodNotAllowed = 'METHOD_NOT_ALLOWED',
  Forbidden = 'FORBIDDEN',
  Unauthorized = 'UNAUTHORIZED',
  InternalError = 'INTERNAL_ERROR',
  SummaryFound = 'SUMMARY_FOUND',
  SummaryNotFound = 'SUMMARY_NOT_FOUND',
  InvalidObjectId = 'INVALID_OBJECT_ID',
  ChannelLeaderboardFound = 'CHANNEL_LEADERBOARD_FOUND',
  UserLeaderboardFound = 'USER_LEADERBOARD_FOUND',
  TokenCreated = 'TOKEN_CREATED',
  VoteSuccess = 'VOTE_SUCCESS',
}