export enum StatusCodePhrases {
  Ok = 'Ok',
  BadRequest = 'BadRequest',
  NotFound = 'NotFound',
  GuildAlreadyExists = 'GuildAlreadyExists',
  GuildCreated = 'GuildCreated',
  GuildFound = 'GuildFound',
  GuildNotFound = 'GuildNotFound',
  GuildUpdated = 'GuildUpdated',
  UserAlreadyExists = 'UserAlreadyExists',
  UserCreated = 'UserCreated',
  UserFound = 'UserFound',
  UserNotFound = 'UserNotFound',
  UserUpdated = 'UserUpdated',
  RouteNotFound = 'RouteNotFound',
  MethodNotAllowed = 'MethodNotAllowed',
  Forbidden = 'Forbidden',
  Unauthorized = 'Unauthorized',
  InternalError = 'InternalError',
  SummaryFound = 'SummaryFound',
  SummaryNotFound = 'SummaryNotFound',
  InvalidObjectId = 'InvalidObjectId',
  ChannelLeaderboardFound = 'ChannelLeaderboardFound',
  UserLeaderboardFound = 'UserLeaderboardFound',
  TokenCreated = 'TokenCreated',
  VoteSuccess = 'VoteSuccess',
}
